export const ADD_COMMENT = 'ADD_COMMENT';
export const CHANGE_NEW_COMMENT_TEXT = 'CHANGE_NEW_COMMENT_TEXT';
export const AUTHENTICATE = 'AUTHENTICATE';
export const FETCH_USERS = 'FETCH_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
